RInside Class Reference
#include <RInside.h>Collaboration diagram for RInside:
Public Member Functions
int parseEval (const std::string &line, SEXP &ans)
int parseEvalQ (const std::string &line)
void assign (const std::vector< std::vector< double > > &mat, const std::string &nam)
void assign (const std::vector< std::vector< int > > &mat, const std::string &nam)
void assign (const std::vector< std::string > &vec, const std::string &nam)
void assign (const std::vector< double > &vec, const std::string &nam)
void assign (const std::vector< int > &vec, const std::string &nam)
void assign (const std::string &txt, const std::string &nam)
RInside (const int argc, const char *const argv[])
~RInside ()
Private Member Functions
void init_tempdir (void)
void init_rand (void)
void autoloads (void)
Private Attributes
MemBuf mb_m
bool verbose_m
Detailed Description
Definition at line 21 of file RInside.h.
Constructor & Destructor Documentation
RInside::RInside (const int argc, const char *const argv[])
Definition at line 20 of file RInside.cpp.
References autoloads(), init_rand(), init_tempdir(), programName, verbose, and verbose_m.
RInside::~RInside ()
Definition at line 14 of file RInside.cpp.
References verbose.
Member Function Documentation
void RInside::assign (const std::string & txt, const std::string & nam)
Definition at line 308 of file RInside.cpp.
void RInside::assign (const std::vector< int > & vec, const std::string & nam)
Definition at line 298 of file RInside.cpp.
void RInside::assign (const std::vector< double > & vec, const std::string & nam)
Definition at line 275 of file RInside.cpp.
void RInside::assign (const std::vector< std::string > & vec, const std::string & nam)
Definition at line 286 of file RInside.cpp.
void RInside::assign (const std::vector< std::vector< int > > & mat, const std::string & nam)
Definition at line 261 of file RInside.cpp.
void RInside::assign (const std::vector< std::vector< double > > & mat, const std::string & nam)
Definition at line 247 of file RInside.cpp.
void RInside::autoloads (void) [private]
Definition at line 102 of file RInside.cpp.
References programName.
Referenced by RInside().
void RInside::init_rand (void) [private]
Definition at line 93 of file RInside.cpp.
Referenced by RInside().
void RInside::init_tempdir (void) [private]
Definition at line 74 of file RInside.cpp.
Referenced by RInside().
int RInside::parseEval (const std::string & line, SEXP & ans)
Definition at line 193 of file RInside.cpp.
References MemBuf::add(), MemBuf::getBufPtr(), mb_m, programName, MemBuf::rewind(), and verbose_m.
Referenced by parseEvalQ().
int RInside::parseEvalQ (const std::string & line)
Definition at line 240 of file RInside.cpp.
References parseEval().
Member Data Documentation
MemBuf RInside::mb_m [private]
Definition at line 23 of file RInside.h.
Referenced by parseEval().
bool RInside::verbose_m [private]
Definition at line 25 of file RInside.h.
Referenced by parseEval(), and RInside().
The documentation for this class was generated from the following files:
src/RInside.h
src/RInside.cpp