MemBuf Class Reference
#include <MemBuf.h>Collaboration diagram for MemBuf:
Classes
struct membuf_st
Public Member Functions
MemBuf (int sizebytes=1024)
~MemBuf ()
void resize ()
void rewind ()
void add (char *buf)
unsigned char * getBufPtr ()
Private Types
typedef struct MemBuf::membuf_st * membuf_t
Private Attributes
membuf_t p_m
Detailed Description
Definition at line 7 of file MemBuf.h.
Member Typedef Documentation
typedef struct MemBuf::membuf_st * MemBuf::membuf_t [private]
Constructor & Destructor Documentation
MemBuf::MemBuf (int sizebytes = 1024)
Definition at line 22 of file MemBuf.cpp.
References MemBuf::membuf_st::buf, MemBuf::membuf_st::count, p_m, programName, MemBuf::membuf_st::size, and verbose.
MemBuf::~MemBuf ()
Definition at line 16 of file MemBuf.cpp.
References p_m, and verbose.
Member Function Documentation
void MemBuf::add (char * buf)
Definition at line 54 of file MemBuf.cpp.
References MemBuf::membuf_st::buf, MemBuf::membuf_st::count, p_m, resize(), and MemBuf::membuf_st::size.
Referenced by RInside::parseEval().
unsigned char* MemBuf::getBufPtr () [inline]
Definition at line 21 of file MemBuf.h.
References MemBuf::membuf_st::buf, and p_m.
Referenced by RInside::parseEval().
void MemBuf::resize ()
Definition at line 39 of file MemBuf.cpp.
References MemBuf::membuf_st::buf, p_m, programName, and MemBuf::membuf_st::size.
Referenced by add().
void MemBuf::rewind ()
Definition at line 50 of file MemBuf.cpp.
References MemBuf::membuf_st::count, and p_m.
Referenced by RInside::parseEval().
Member Data Documentation
membuf_t MemBuf::p_m [private]
Definition at line 14 of file MemBuf.h.
Referenced by add(), getBufPtr(), MemBuf(), resize(), rewind(), and ~MemBuf().
The documentation for this class was generated from the following files:
src/MemBuf.h
src/MemBuf.cpp