#!/bin/sh

set -e

if [ ! -d src ]; then
    echo "Not above src/"
    exit -1
fi

cwd=$(pwd)

version=$(r -e'cat(as.character(read.dcf("DESCRIPTION")[,"Version"]))')
echo "Working on version $version"


if [ -x /usr/bin/doxygen ]; then
    if [ -d inst/doc ]; then
        cd inst/doc
        rm -rf html/ latex/ man/
        cd ${cwd}
    fi
    cd src && ln -s ../inst/examples . && cd -

    ## see FAQ 17 for doxygen
    ( cat doxyfile ; echo PROJECT_NAME="\"RInside Version ${version}\"" ) | doxygen -

    rm src/examples
    cd ${cwd}
    pwd

    cd inst/doc
    zip -9r rinside-doc-html.zip html/
    zip -9r rinside-doc-man.zip man
    zip -9r rinside-doc-latex.zip latex
    if [ -d ~/www/code/rinside/ ]; then
	mv -v rinside-doc-*.zip ~/www/code/rinside/
	rsync --delete -avu html ~/www/code/rinside/
    fi
    cd ${cwd}

    cd inst/doc/latex
    pdflatex refman
    pdflatex refman
    if [ -d ~/www/code/rinside/ ]; then
	cp -vax refman.pdf ~/www/code/rinside/RInside_refman.pdf
    fi
    cd ${cwd}

    if [ -d inst/doc ]; then
        cd inst/doc
        rm -rf html/ latex/ man/
        cd ..
        rm doc/doxygen_sqlite3.db
        rmdir doc
        cd ${cwd}
    fi

#    if [ -d ~/www/code/rinside/ ]; then
#	cp -vax inst/doc/RInside-*.pdf ~/www/code/rinside
#    fi
#    cd ${cwd}

fi
