.TH "src/MemBuf.h" 3 "12 Sep 2009" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MemBuf.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMemBuf\fP"
.br
.ti -1c
.RI "struct \fBMemBuf::membuf_st\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code.
