.TH "MemBuf::membuf_st" 3 "12 Sep 2009" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemBuf::membuf_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "unsigned char * \fBbuf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file MemBuf.h.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char* \fBMemBuf::membuf_st::buf\fP"
.PP
Definition at line 12 of file MemBuf.h.
.PP
Referenced by MemBuf::add(), MemBuf::getBufPtr(), MemBuf::MemBuf(), and MemBuf::resize().
.SS "int \fBMemBuf::membuf_st::count\fP"
.PP
Definition at line 11 of file MemBuf.h.
.PP
Referenced by MemBuf::add(), MemBuf::MemBuf(), and MemBuf::rewind().
.SS "int \fBMemBuf::membuf_st::size\fP"
.PP
Definition at line 10 of file MemBuf.h.
.PP
Referenced by MemBuf::add(), MemBuf::MemBuf(), and MemBuf::resize().

.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code.
