.TH "src/RInside.cpp" 3 "12 Sep 2009" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RInside.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'RInside.h'\fP
.br
\fC#include <sys/time.h>\fP
.br
\fC#include 'RInsideEnvVars.h'\fP
.br
\fC#include 'RInsideAutoloads.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBverbose\fP = false"
.br
.ti -1c
.RI "const char * \fBprogramName\fP = 'RInside'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* \fBprogramName\fP = 'RInside'"
.PP
Definition at line 12 of file RInside.cpp.
.PP
Referenced by RInside::autoloads(), MemBuf::MemBuf(), RInside::parseEval(), MemBuf::resize(), and RInside::RInside().
.SS "bool \fBverbose\fP = false"
.PP
Definition at line 11 of file RInside.cpp.
.PP
Referenced by MemBuf::MemBuf(), RInside::RInside(), MemBuf::~MemBuf(), and RInside::~RInside().
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code.
