// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RInside.h"
#include <Rcpp.h>

using namespace Rcpp;

// showCompiler
void showCompiler();
RcppExport SEXP _RInside_showCompiler() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    showCompiler();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RInside_showCompiler", (DL_FUNC) &_RInside_showCompiler, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RInside(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
